import type { Metadata } from "next";
import type { Viewport } from "next";
import "./globals.css";
import BurgerButton from "@/components/BurgerButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1.0,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-background text-foreground font-sans antialiased`}>
        <div className="flex flex-col gap-12 min-h-screen text-gray-200">
          <header className="w-auto h-24 bg-gray-800 flex justify-between items-center shadow-sm">
            <div className="flex gap-12 ml-4">
              <span className="text-2xl font-bold text-cyan-300">logo</span>
            </div>
            <ul className="cursor-pointer flex gap-4 items-center">
              <li className="bg-sky-800 hover:bg-sky-700 rounded-xl p-2 transition-colors">
                Hamburguer menu
              </li>
              <li className="bg-sky-800 hover:bg-sky-700 rounded-xl mr-2 p-2 transition-colors">
                Last updates
              </li>
            </ul>
            <BurgerButton></BurgerButton>
          </header>
          <div className="px-4 max-w-3xl mx-auto">{children}</div>
        </div>
        <footer className="text-center text-sm bg-gray-800  p-3 mt-6">
          <span>Made by: </span>© 2025 João Victor - Pela vontade de
          compartilhar, aprender e, se possível, contribuir.
        </footer>
      </body>
    </html>
  );
}
